// Taiwan Civic & Sovereignty Map data source
// 只放公開、可查證的組織地址與主辦方公開活動。不要放私人住址、未公開聚會或個人追蹤資料。
// 座標若不確定，請先用 OpenStreetMap / Google Maps 核對，再更新 lat/lng。
window.TCSM_DATA = {
  updatedAt: "2026-06-25",
  sources: [
    { title: "內政部政黨資訊網", url: "https://party.moi.gov.tw/" },
    { title: "內政部人民團體數位櫃檯", url: "https://grouptw.moi.gov.tw/searchGroup" },
    { title: "司法院法人登記公告", url: "https://www.judicial.gov.tw/tw/lp-144-1.html" },
    { title: "民主進步黨官方網站", url: "https://www.dpp.org.tw/" },
    { title: "台灣基進活動資訊", url: "https://statebuilding.tw/events/" },
    { title: "台灣獨立建國聯盟", url: "https://wufi.org.tw/" }
  ],
  categories: [
    { key: "all", label: "全部" },
    { key: "party", label: "政黨／黨部" },
    { key: "civic", label: "協會／組織" },
    { key: "foundation", label: "基金會" },
    { key: "event", label: "公開活動" }
  ],
  organizations: [
    {
      id: "dpp-central",
      category: "party",
      name: "民主進步黨中央黨部",
      englishName: "Democratic Progressive Party HQ",
      type: "政黨／中央黨部",
      address: "臺北市中正區北平東路30號10樓",
      lat: 25.0459,
      lng: 121.5261,
      host: "民主進步黨",
      coHost: "依各活動公告",
      demand: "民主治理、政黨外交、台灣主體與公共政策倡議。",
      eligibility: "公開活動依主辦單位公告；黨務、營隊或培訓可能限制黨籍、年齡或專業背景。",
      officialUrl: "https://www.dpp.org.tw/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E5%B8%82%E4%B8%AD%E6%AD%A3%E5%8D%80%E5%8C%97%E5%B9%B3%E6%9D%B1%E8%B7%AF30%E8%99%9F10%E6%A8%93",
      sourceLabel: "內政部政黨資訊網／民進黨官網",
      tags: ["綠營", "政黨", "中央黨部", "Team Taiwan"],
      freshness: "地址資料請以內政部與官網最新公告為準"
    },
    {
      id: "statebuilding-kaohsiung",
      category: "party",
      name: "台灣基進主事務所",
      englishName: "Taiwan Statebuilding Party HQ",
      type: "政黨／主事務所",
      address: "高雄市三民區大順二路276號",
      lat: 22.6465,
      lng: 120.3252,
      host: "台灣基進",
      coHost: "依各活動公告",
      demand: "堅持台灣主體性，推動民主深化與國家正常化。",
      eligibility: "公開活動多以報名制為主；請以活動頁與表單公告為準。",
      officialUrl: "https://statebuilding.tw/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E9%AB%98%E9%9B%84%E5%B8%82%E4%B8%89%E6%B0%91%E5%8D%80%E5%A4%A7%E9%A0%86%E4%BA%8C%E8%B7%AF276%E8%99%9F",
      sourceLabel: "內政部政黨資訊網／台灣基進官網",
      tags: ["台灣主體", "國家正常化", "政黨", "年輕化"],
      freshness: "地址資料請以內政部與官網最新公告為準"
    },
    {
      id: "tsu-central",
      category: "party",
      name: "台聯黨主事務所",
      englishName: "Taiwan Solidarity Union Office",
      type: "政黨／主事務所",
      address: "臺北市中正區紹興北街35號4樓之4",
      lat: 25.0447,
      lng: 121.5258,
      host: "台聯黨",
      coHost: "依各活動公告",
      demand: "本土政治與台灣主體相關公共倡議。",
      eligibility: "依主辦單位公開公告。",
      officialUrl: "https://party.moi.gov.tw/PartyMainContent.aspx?n=16100&s=154&sms=13073",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E5%B8%82%E4%B8%AD%E6%AD%A3%E5%8D%80%E7%B4%B9%E8%88%88%E5%8C%97%E8%A1%9735%E8%99%9F4%E6%A8%93%E4%B9%8B4",
      sourceLabel: "內政部政黨資訊網",
      tags: ["本土派", "政黨", "公開登記"],
      freshness: "地址資料請以內政部最新公告為準"
    },
    {
      id: "npp-central",
      category: "party",
      name: "時代力量主事務所",
      englishName: "New Power Party Office",
      type: "政黨／主事務所",
      address: "臺北市中山區新生北路2段31-1號3樓之5",
      lat: 25.0546,
      lng: 121.5273,
      host: "時代力量",
      coHost: "依各活動公告",
      demand: "民主監督、改革政治與公共議題倡議。",
      eligibility: "依主辦單位公開公告。",
      officialUrl: "https://party.moi.gov.tw/PartyMainContent.aspx?n=16100&s=326&sms=13073",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E5%B8%82%E4%B8%AD%E5%B1%B1%E5%8D%80%E6%96%B0%E7%94%9F%E5%8C%97%E8%B7%AF2%E6%AE%B531-1%E8%99%9F3%E6%A8%93%E4%B9%8B5",
      sourceLabel: "內政部政黨資訊網",
      tags: ["民主監督", "政黨", "改革派"],
      freshness: "地址資料請以內政部最新公告為準"
    },
    {
      id: "sdp-central",
      category: "party",
      name: "社會民主黨主事務所",
      englishName: "Social Democratic Party Office",
      type: "政黨／主事務所",
      address: "臺北市中山區林森北路100號8樓之4",
      lat: 25.0496,
      lng: 121.5247,
      host: "社會民主黨",
      coHost: "依各活動公告",
      demand: "社會民主、平權、公共政策與公民參與。",
      eligibility: "依主辦單位公開公告。",
      officialUrl: "https://party.moi.gov.tw/PartyMainContent.aspx?n=16100&s=328&sms=13073",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E5%B8%82%E4%B8%AD%E5%B1%B1%E5%8D%80%E6%9E%97%E6%A3%AE%E5%8C%97%E8%B7%AF100%E8%99%9F8%E6%A8%93%E4%B9%8B4",
      sourceLabel: "內政部政黨資訊網",
      tags: ["社會民主", "平權", "政黨"],
      freshness: "地址資料請以內政部最新公告為準"
    },
    {
      id: "wufi-taiwan",
      category: "civic",
      name: "台灣獨立建國聯盟",
      englishName: "World United Formosans for Independence",
      type: "政治組織／公開活動來源",
      address: "臺北市中正區青島西路11號14樓之1",
      lat: 25.0450,
      lng: 121.5179,
      host: "台灣獨立建國聯盟",
      coHost: "依各活動公告",
      demand: "台灣主權、正名制憲、民主自由與國家正常化。",
      eligibility: "公開講座、論壇或影展依活動公告；部分活動可能需事先報名。",
      officialUrl: "https://wufi.org.tw/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E8%87%BA%E5%8C%97%E5%B8%82%E4%B8%AD%E6%AD%A3%E5%8D%80%E9%9D%92%E5%B3%B6%E8%A5%BF%E8%B7%AF11%E8%99%9F14%E6%A8%93%E4%B9%8B1",
      sourceLabel: "台灣獨立建國聯盟官網／公開粉專資訊",
      tags: ["台獨", "正名制憲", "民主自由", "公開活動"],
      freshness: "地址與活動請以官網、公開粉專最新公告為準"
    },
    {
      id: "tnc-foundation",
      category: "foundation",
      name: "台灣制憲基金會／辜寬敏基金會",
      englishName: "Taiwan New Constitution Foundation / Koo Kwang-ming Foundation",
      type: "財團法人／基金會",
      address: "臺北市，詳細地址請以法人登記與官方公告為準",
      lat: 25.0478,
      lng: 121.5170,
      host: "台灣制憲基金會／辜寬敏基金會",
      coHost: "依各活動公告",
      demand: "台灣新憲法、國家正常化、轉型正義與公共討論。",
      eligibility: "公開活動依主辦單位公告；基金會登記資料請查司法院法人登記公告。",
      officialUrl: "https://tnc-ref.org.tw/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E5%8F%B0%E7%81%A3%E5%88%B6%E6%86%B2%E5%9F%BA%E9%87%91%E6%9C%83",
      sourceLabel: "司法院法人登記公告／基金會公開資訊",
      tags: ["制憲", "基金會", "國家正常化", "轉型正義"],
      freshness: "此筆以公開主題與法人登記入口為主，地址請人工覆核後再公開精準點位"
    }
  ],
  events: [
    {
      id: "statebuilding-salon-taipei-20260626",
      category: "event",
      name: "基進沙龍＠台北｜從日本經驗，反思台灣地方創生",
      englishName: "Statebuilding Salon Taipei",
      type: "演講／座談",
      address: "台灣獨立建國聯盟，臺北市中正區青島西路11號14樓之1附近",
      lat: 25.0450,
      lng: 121.5179,
      radiusMeters: 650,
      host: "台灣基進",
      coHost: "活動場地方／協力單位依報名頁公告",
      demand: "透過日本經驗討論地方創生與台灣公共議題，讓理念落地、讓地方有感。",
      time: "2026-06-26 19:00–21:00",
      eligibility: "公開報名，名額與入場規則依報名表單為準。",
      officialUrl: "https://statebuilding.tw/events/",
      signupUrl: "https://statebuilding.tw/events/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E5%8F%B0%E7%81%A3%E7%8D%A8%E7%AB%8B%E5%BB%BA%E5%9C%8B%E8%81%AF%E7%9B%9F",
      sourceLabel: "台灣基進活動資訊頁",
      tags: ["即將舉行", "台北", "地方創生", "座談"],
      freshness: "活動時間與報名狀態請以台灣基進活動頁為準"
    },
    {
      id: "dpp-diplomacy-camp-20260710",
      category: "event",
      name: "民進黨2026外交培力營",
      englishName: "DPP 2026 Diplomacy Training Camp",
      type: "營隊／培力",
      address: "活動地點依報名簡章公告；網站以中央黨部作為資訊入口定位",
      lat: 25.0459,
      lng: 121.5261,
      radiusMeters: 900,
      host: "民主進步黨國際部",
      coHost: "依活動簡章公告",
      demand: "拓展政黨外交、提升國際視野、培力國際人才；聚焦經濟安全、區域防衛、台美交流。",
      time: "2026-07-10 至 2026-07-20；報名時間 2026-03-30 至 2026-04-19",
      eligibility: "官網公告號召具國際關係、經貿、國防安全、公共政策等專長的黨籍夥伴報名。",
      officialUrl: "https://www.dpp.org.tw/news/contents/8582",
      signupUrl: "https://www.dpp.org.tw/news/contents/8582",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E6%B0%91%E4%B8%BB%E9%80%B2%E6%AD%A5%E9%BB%A8%E4%B8%AD%E5%A4%AE%E9%BB%A8%E9%83%A8",
      sourceLabel: "民進黨官方網站",
      tags: ["青年培力", "政黨外交", "台美交流", "營隊"],
      freshness: "活動地點與資格請以報名簡章為準"
    },
    {
      id: "wufi-events-feed",
      category: "event",
      name: "台灣獨立建國聯盟活動訊息入口",
      englishName: "WUFI Public Events Feed",
      type: "公開活動入口",
      address: "台灣獨立建國聯盟活動依官網公告；常見形式含論壇、影展、講座、遊行倡議。",
      lat: 25.0450,
      lng: 121.5179,
      radiusMeters: 800,
      host: "台灣獨立建國聯盟及相關協力團體",
      coHost: "依各活動公告",
      demand: "主權、人權、轉型正義、民主價值與國家正常化公共討論。",
      time: "請以官網活動訊息最新公告為準",
      eligibility: "多數公開活動依公告或報名規則參加；現場規範以主辦方公告為準。",
      officialUrl: "https://wufi.org.tw/",
      signupUrl: "https://wufi.org.tw/",
      mapUrl: "https://www.google.com/maps/search/?api=1&query=%E5%8F%B0%E7%81%A3%E7%8D%A8%E7%AB%8B%E5%BB%BA%E5%9C%8B%E8%81%AF%E7%9B%9F",
      sourceLabel: "台灣獨立建國聯盟官網",
      tags: ["活動入口", "主權", "人權", "轉型正義"],
      freshness: "此筆為活動入口，不代表單一固定活動；請點官方連結查最新場次"
    }
  ]
};
